BioDynaMo/biodynamo

src/diffusion_grid.h

when diffusion coef and decay constant are 0

skip diffusion and gradient calculation

---

doc/user_guide/docs/hello_world.md

I think there was an error saying to add to the "construct" function as new bdm .h files do not come with any function named "construct", I think saying to add the changes to the constructor instead is a little more clear.

Editing of "Constructor" part of the tutorial

---

doc/user_guide/docs/visualization.md

Adding an addendum that one can also use a pipeline to make the project, run the file and finally visualise it in paraview all from the terminal.

Pipeline visualisation.

---

src/core/simulation.cc
test/system/backup_restore.sh

- Logic to check for `-b` and `-r` individually
- backup_restore test updated

Fix command argument for restoring

---

prerequisites.sh

to not install the prerequisites.

Change prerequisites.sh exit code when answering "no".

---

src/core/grid.h

Hide memory latencies
Batch / vectorize distance calculation

Improve performance of Grid::ForEachNeighbor

---

src/core/gpu/gpu_helper.h
src/core/param/command_line_options.cc
src/core/simulation.cc
test/system/cell_division_gpu/src/cell_division_gpu.h

E.g. `cell_division_gpu --opencl` to run on GPU using OpenCL.
It also fixes a compilation error when OpenCL / CUDA is enabled.

Update GPU benchmark

---

CMakeLists.txt
cmake/Website.cmake
doc/dev_guide/build.md

Check if Doxygen is installed before attempting to build the website

Add website option in CMake

---

.github/workflows/centos-ci.yml
.github/workflows/centos-system-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/ubuntu-ci.yml
.github/workflows/ubuntu-system-ci.yml
cli/new_command.py

Cache pyenv and third party libraries for faster workflows

Install BioDynaMo only on schedule; not on PRs

---

CMakeLists.txt
cli/common.py
cli/demo_command.py
cli/launcher.sh
cli/new_command.py
cli/run_command.py
cmake/FindLibroadrunner.cmake
cmake/FindROOT.cmake
cmake/Installation.cmake
cmake/Notebooks.cmake
cmake/UseBioDynaMo.cmake.in
cmake/env/thisbdm.fish
cmake/env/thisbdm.sh
src/core/visualization/paraview/insitu_pipeline.h
test/system/backup_restore.sh
test/system/makefile_project.sh
util/benchmark/benchmark.sh
util/installation/common/util.sh

The installation directory can now be set with `-DCMAKE_INSTALL_PREFIX`
`BDMSYS` should be used instead of `BDM_INSTALL_DIR`

Fix installation directory issue. Remove BDM_INSTALL_DIR.

---

cmake/selection-libbiodynamo.xml
demo/parameters/CMakeLists.txt
demo/parameters/src/parameters.cc
demo/parameters/src/parameters.h
doc/sidebars/userguide.yaml
doc/user_guide/parameter.md
doc/user_guide/simulation_parameter_tutorial.md
src/core/param/command_line_options.cc
src/core/param/command_line_options.h
src/core/param/module_param.h
src/core/param/param.cc
src/core/param/param.h
src/core/simulation.cc
src/core/simulation.h
src/core/util/string.h
src/neuroscience/param.cc
src/neuroscience/param.h
test/unit/core/param/param_test.cc
test/unit/core/param/param_test.h
test/unit/core/simulation_test.cc
test/unit/core/visualization/paraview_adaptor_test.cc
third_party/json.hpp

* Add inline-config command line parameter.
* Add command line parameter to output default json parameters.
* Add command line parameter to convert a TOML config file into
JSON format.
* Add parameter values to simulation metadata output.
* Add simulation parameter tutorial

Add support for JSON config files

---

cmake/selection-libbiodynamo.xml
cmake/selection.xml
src/core/default_force.cc
src/core/visualization/root/adaptor.h
src/neuroscience/event/event.cc
src/neuroscience/event/neurite_bifurcation_event.h
src/neuroscience/event/neurite_branching_event.h
src/neuroscience/event/new_neurite_extension_event.h
src/neuroscience/event/side_neurite_extension_event.h
src/neuroscience/event/split_neurite_element_event.h
src/neuroscience/module.cc
src/neuroscience/module.h
src/neuroscience/neurite_element.h
src/neuroscience/neuron_or_neurite.cc
src/neuroscience/neuron_or_neurite.h
src/neuroscience/neuron_soma.cc
src/neuroscience/neuron_soma.h
src/neuroscience/param.cc
src/neuroscience/param.h
test/unit/core/default_force_test.cc
test/unit/neuroscience/mechanical_interaction_test.cc
test/unit/neuroscience/neurite_retraction_test.cc
test/unit/neuroscience/neuron_soma_test.cc
test/unit/neuroscience/param_test.cc

pull request for remove "experimental" from namespace

Remove experimental from namespace

---

.github/workflows/centos-ci.yml
.github/workflows/centos-system-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/ubuntu-ci.yml
.github/workflows/ubuntu-system-ci.yml

Replace set-env with environment file

---

.github/workflows/centos-system-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/ubuntu-system-ci.yml
cmake/BioDynaMo.cmake
cmake/FindROOT.cmake
cmake/Testing.cmake
cmake/bdm-dictionary
cmake/utils.cmake
demo/makefile_project/Makefile
src/core/util/jit.cc
util/makefile-build/bdm-code-generation

Fix installation issues related to paths pointing to the build location

---

src/core/agent/agent_pointer.h
src/core/agent/agent_uid.h
src/core/diffusion/diffusion_grid.cc
test/unit/core/behavior/behavior_test.cc

Reported by -fsanitize=undefined flag using g++ 9.3 on ubuntu 20.04

Fix undefined behavior

---

src/core/diffusion/diffusion_grid.cc
src/core/environment/uniform_grid_environment.h
src/core/memory/memory_manager.cc
test/unit/core/resource_manager_test.cc

These are some small changes that I made to address the undefined behaviour (clang `-fsanitize=usigned-integer-overflow`). I believe that the commit "Remove SIMD" should not be merged but let me know what you think.

Fix undefined behaviour

---

src/core/agent/agent.cc
src/core/agent/agent.h

introduced in 2a64431a1fef29dc1ba48ca6cffccc63b8e6569a

Fix performance regression

---

CMakeLists.txt
util/installation/osx/prerequisites.sh

Recently, some users had trouble with building BioDynaMo. One of them was having trouble providing the right python environment on ubuntu. To avoid that in the future, I noted down the commands that are used ubuntu/centos CI to set the right environment. Ultimately, that's what also resolved the problem for the user back than.
Another user forgot to install Xcode on macOS which we did not test for so far. Now there is a check in place to test for an Xcode installation. The same user had the problem that the homebrew package manager was not working properly and did not install all necessary packages. I added two loops that check for each brew formula individually if it has been installed or not. (Note that this adds some additional runtime to the prerequisites script.) The output is a …

Installation

---

test/unit/core/resource_manager_test.cc

Clang 13.0 somehow was not able to handle the `#pragma omp critical` in the lambda function and had segmentation fault. The crash report shows the following:
```bash
[...]
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [29578]
[...]
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   clang                               0x0000000104844328 (anonymous namespace)::CGOpenMPInlinedRegionInfo::getContextValue() const + 4
1   clang                               0x0000000102f85d28 …
```

Reactivate `ForEachAgentParallelFilter` test on macOS

---

.github/workflows/repostory-checks.yml
demo/pyramidal_cell/src/pyramidal_cell.h
src/core/diffusion/diffusion_grid.cc
src/core/gpu/helper_math_double.h
src/core/operation/reduction_op.cc
test/unit/core/environment/uniform_grid_environment_test.cc
test/unit/core/resource_manager_test.h
util/housekeeping/run-clang-format.sh

Add GHA that quickly checks the code style with clang-format.

Add clang-format code-style check to GHA

---

CMakeLists.txt

Fixed the build issue on my MacBook.

Remove march=native for Apple

---

.github/workflows/sonar-source.yml
sonar-project.properties

This PR (+some invisible work behind the scenes) brings `Sonar Cloud` source code checks to the BioDynaMo repository. The results of the analysis are available via a [dashboard](https://sonarcloud.io/project/configuration?id=BioDynaMo_biodynamo) accessible for all to see and for all developers to take action.

Add quality checks with `Sonar Cloud`

---

src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
test/unit/core/diffusion_test.cc

Added check for decay rate in diffusion grid to prevent the concentration from going below 0

Added check for decay rate in diffusion grid

---

.github/workflows/centos-system-ci.yml
util/installation/centos-7/prerequisites.sh

Fixes python dependencies for CentOS and BDM notebooks. Thanks @Senui for pointing that out!

Fix notebook packages on CentOS

---

CMakeLists.txt

Co-authored-by: Lukas Breitwieser <lukas.breitwieser@cern.ch>

Fix Python libraries on macOS

---

src/core/behavior/secretion.h
src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
test/unit/core/diffusion_test.cc

Add the different modes to interact with the continuum:
- additive
- exponential
- logistic

Add different interaction modes

---

src/core/diffusion/diffusion_grid.cc

$$
( \frac{\partial }{\partial t} - D\ \nabla^2 + \lambda)\ u = 0, \ \ \ D, \lambda \in \mathbb{R}, 
$$
**Stability condition:**
Derived via von Neumann stability analysis (https://en.wikipedia.org/wiki/Von_Neumann_stability_analysis) 
$$
\left( \lambda + \frac{12 \cdot D}{h^2} \right) \Delta t \leq 2
$$
**Decay check:**
Derived by assuming positivity of u^n and demanding positivity of u^{n+1}
$$
1 - \left( \lambda + \frac{6 \cdot D} {h^2} \right) \Delta t \geq 0
$$

Modify stability condition and decay check

---

src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
test/unit/core/diffusion_test.cc

Cells are often modeled to consume amounts of glucose (or others), while diffusion is often a scalar field describing a concentration. To convert to appropriate units, this PR adds a `bool scale_with_resolution`, which scales the amount as 
```
double amount {x};
amount /= box_lenght_ * box_lenght_ * box_lenght_;
```
This effectively gives you a switch to make the simulation outcome independent of `resolution_`.
------------------------------------------------------------------------------------------------
<summary><b>The BDM PR checklist</b></summary>
First time contributor? Make sure to review our contributing guidelines:
* [Code Quality](https://biodynamo.org/docs/devguide/code_quality/)
* [C++ Style Guide](https://biodynamo.org/docs/devguide/contribute/)
`.gitignore` file
and …

Add resolution independent version of `DG::ChangeConcentrationBy`

---

.github/workflows/centos-ci.yml
.github/workflows/centos-system-ci.yml
.github/workflows/gitpod.yml
.github/workflows/macos-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/repostory-checks.yml
.github/workflows/sonar-source.yml
.github/workflows/ubuntu-ci.yml
.github/workflows/ubuntu-system-ci.yml
doc/dev_guide/contribute.md

Finalizing move from Slack to Discord. Remove CI webhooks for Slack. Adjust contribute.md accordingly.

Remove Slack notifications from CI

---

src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
test/unit/core/diffusion_init_test.cc

Parallelise initialisation of the diffusion grids
<details>
<summary><b>The BDM PR checklist</b></summary>
First time contributor? Make sure to review our contributing guidelines:
* [Code Quality](https://biodynamo.org/docs/devguide/code_quality/)
* [C++ Style Guide](https://biodynamo.org/docs/devguide/contribute/)
`.gitignore` file
and functions have full Doxygen-style documentation in source comments.
Documentation should include descriptions of member data, function
arguments and return values, template parameters, and prerequisites for
calling new functions.
being transferred or lent with the call.
threading affects your code (e.g. check if it yields the same results in
parallel regions with and without `OMP_NUM_THREADS=1`)
to be verified by reviewer)
[C++ style …

Parallelize `DG::RunInitializers`

---

cli/main.py
cli/view_command.py
doc/user_guide/visualization.md

Add a wrapper for opening the latest ParaView state for a smoother development workflow.
Workflow including visualizing:
```
cd <path-to-my-bdm>
git pull
git checkout bdm-view
cd build
cmake .. & make -j <num-cores>
. bin/thisbdm.sh
cd <some-directory-you-like>
bdm demo soma_clustering
cd soma_clustering
bdm run
bdm view
```

Add `bdm view` to CLI

---

.github/workflows/sonar-source.yml

Update SonarCloud CI

---

src/core/diffusion/diffusion_grid.h
src/core/stdfilesystem.h
src/core/util/git_tracker.cc
test/unit/core/scheduler_test.cc

- Fixed errors caused by missing/wrong filesystem header on both macOS and CentOS
- Fixed warnings raised by Xcode 15 on macOS 14.0 (Sonoma)

Experimental fix

---

demo/binding_cells/CMakeLists.txt
demo/cell_division/CMakeLists.txt
demo/diffusion/CMakeLists.txt
demo/epidemiology/CMakeLists.txt
demo/flocking/CMakeLists.txt
demo/gene_regulation/CMakeLists.txt
demo/multiple_simulations/CMakeLists.txt
demo/parameters/CMakeLists.txt
demo/pyramidal_cell/CMakeLists.txt
demo/sbml_integration/CMakeLists.txt
demo/soma_clustering/CMakeLists.txt
demo/tumor_concept/CMakeLists.txt
test/system/backup_restore/CMakeLists.txt
test/system/cell_division_gpu/CMakeLists.txt
test/system/multi_simulation/CMakeLists.txt
test/system/substance_initialization/CMakeLists.txt

Use same minimum CMake version throughout the project

Unify `CMake` versions

---

demo/mars/src/CelestialObjects.h
demo/newtons_law_test/src/CelestialObjects.h
demo/solar_system/src/CelestialObjects.h

This pull request addresses code style issues in the **mars**, **newtons_law_test**, and **solar_system** demos to ensure they pass the **repository-check / code-style** workflow on GitHub Actions.

Fix demo code style
