doc/user_guide/docs/visualization.md

To make it more clear to users that there are two parts to the bdm.toml file I believe the simulation part should also be included in this example.

Add Simulation section to bdm.toml file example.

---

src/core/container/math_array.h
test/unit/core/container/math_array_test.cc

It provides a similar interface to the one of `std::array<T, std::size_t>`, but it also overloads mathematical operations. For instance, it is possible to do now:
```c++
MathArray a{1,2,3}; 
MathArray b{1,1,1};
auto c = a+b; // c <-- {2,3,4}
a.Sum(); // 6
```
Changes:
* Overload ++ and --;
* Overload +, -, +=, -=, * and *= (both for MathArray and scalars);
* Overload / and /= (only for scalars);
* Add Sum(), Norm(), Normalize() methods;
* Add MathArray unit tests.

Add MathArray container.

---

src/core/substance_initializers.h

It seems the y axis was being used here accidentally instead of the z axis.

Incorrecct axis used

---

util/installation/ubuntu-16.04/Dockerfile
util/run-inside-docker.sh

This is needed to make mkdoc work. It prevents this error from happening:
```bash
Traceback (most recent call last):
File "/home/testuser/.local/bin/mkdocs", line 11, in <module>
sys.exit(cli())
File "/home/testuser/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/home/testuser/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
_verify_python3_env()
File "/home/testuser/.local/lib/python3.5/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
This system …
```

Set Docker locale on Ubuntu image.

---

CMakeLists.txt
cmake/FindROOT.cmake

This way it will be more easy to relocate the build directory and use biodynamo from there. Not having the rpath will force us to source anytime the `thisbdm.sh` script, which is, however, a mandatory
step in order to use the library.

Change RPath such to relocate easily the build directory.

---

CMakeLists.txt
cmake/UseBioDynaMo.cmake.in
src/core/gpu/displacement_op_cuda_kernel.cu
src/core/gpu/displacement_op_cuda_kernel.h
src/core/gpu/gpu_helper.h
src/core/grid.h
src/core/operation/displacement_op.h
src/core/operation/displacement_op_cuda.h
src/core/operation/displacement_op_opencl.h
src/core/resource_manager.h
test/system/cell_division_gpu/src/cell_division_gpu.h
test/unit/core/operation/displacement_op_gpu_test.cc

The GPU code is refactored to be compatible with the dynamic runtime of BioDynaMo. At the moment there are two restrictions:
1. Only 1 NUMA domain is supported. We throw a fatal error when we detect more than 1 NUMA domain.
2. Only sphere-sphere interactions are supported. We throw a fatal error when we detect a non-spherical object in the simulation.
Since the dynamic runtime does not have the state of simulation objects in contiguous arrays (SoA layout), we perform a copy operations prior to dispatching the kernel to the GPU such we again have a contiguous array layout.

Refactor GPU code for dynamic runtime

---

src/core/util/numa.h

On systems without libnuma support we store data on the lowest NUMA domain. Therefore, the value of `status` in `numa_move_pages` should be set to zero.

Fix numa issue on systems without libnuma support

---

.travis.yml

The current solution is outdated from the time that we ran all our builds directly on the Travis machines. Now it's only the OS X machines where this is the case; for the others, we run inside docker.

Update travis failure output command

---

util/installation/travis-osx/prerequisites.sh

Travis was failing because brew was not creating symlinks for Python 3:
```
==> Upgrading python3 
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.6_1.mojave.bottl
==> Downloading from https://akamai.bintray.com/64/643d627c2b4fc03a3286c397d2992
######################################################################## 100.0%
==> Pouring python-3.7.6_1.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink Frameworks/Python.framework/Headers
Target /usr/local/Frameworks/Python.framework/Headers
is a symlink belonging to python@2. You can unlink it:
brew unlink python@2
To force the link and overwrite all conflicting files:
brew link --overwrite python
```
Since we still need …

Fix missing Python 3 symlinks with homebrew on Travis

---

cmake/BioDynaMo.cmake
cmake/env/thisbdm.sh
cmake/utils.cmake

This alleviates users from having to have rootlogon.C in the current working directory for it to be picked up by ROOT.
Also, we removed unnecessary lines in rootlogon.C and added some useful ones. Mainly the #define USE_DICT line avoids segmentation faults from happing in rootcling / notebook (could break the one-definition rule): https://root-forum.cern.ch/t/program-crashes-in-cling-only-when-dictionaries-are-built/37178/18

Automatically load our rootlogon.C upon root invocation

---

demo/soma_clustering/src/soma_clustering.h
demo/tumor_concept/src/tumor_concept.h
src/core/execution_context/in_place_exec_ctxt.cc
src/core/execution_context/in_place_exec_ctxt.h
src/core/grid.h
src/core/param/param.cc
src/core/param/param.h
src/core/sim_object/sim_object.h
src/core/util/spinlock.h
src/neuroscience/neurite_element.h
src/neuroscience/neuron_or_neurite.h
src/neuroscience/neuron_soma.cc
src/neuroscience/neuron_soma.h
test/unit/core/execution_context/in_place_exec_ctxt_test.cc
test/unit/core/simulation_test.cc

This thread-safety mechanism relies on the user to specify which simulation
objects must not be modified at the same time.
The current solution locks the whole microenvironment.
Param::thread_safety_mechanism_ lets users decide which ones they prefer
(kNone, kUserSpecified, or kAutomatic)

Add fine-grained thread safety mechanism

---

.github/workflows/centos-system-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/ubuntu-system-ci.yml
util/install

There is no single way with Github Actions to obtain the branch
name for both pull requests and schedule workflows. We set an
environmental variable (GHA_BRANCH_NAME) depending on the workflow
event name

Fix query of current branch name in GHA for scheduled workflows

---

cmake/Testing.cmake
src/core/container/sim_object_vector.h
src/core/environment/uniform_grid_environment.h
src/core/operation/load_balancing_op.h
src/core/operation/operation.cc
src/core/operation/operation.h
src/core/scheduler.cc
src/core/scheduler.h
src/core/sim_object/sim_object.h
test/unit/core/container/sim_object_vector_test.cc
test/unit/core/operation/operation_test.cc
test/unit/core/scheduler_test.cc
test/unit/core/scheduler_test.h
test/unit/neuroscience/mechanical_interaction_test.cc

* Introduce three types of operations in Scheduler:
1) PreScheduledOp
2) ScheduledOp
3) PostScheduledOp
There are currently several operations that need to be run
before (PreScheduledOp) and after (PostScheduledOp) the regular
operations (ScheduledOp). Instead of having them floating around
in Scheduler, we create separate lists for each type of operation
This way, it is possible to schedule, unschedule and reschedule
any operation using the same interface as we did before
* Load and balancing should be a PostScheduledOp rather than a
PreScheduleOp (SoHandles could be invalidated). Added a unit test
for this

Improve scheduling of operations. Fix ordering issues.

---

cmake/env/sh_functions/__bdm_zsh_completions
cmake/env/thisbdm.fish
cmake/env/thisbdm.sh
util/installation/common/util.sh

- [multiple pyenv shims in path](https://github.com/pyenv/pyenv/issues/969) mitigation 
- fix thisbdm.fish oversight (clearing of previous pyenv env. vars was completely missing)
- minimal completion for biodynamo command on bash and zsh
- conform to 80x25 terminal window for warnings and errors in modified files
- util.sh minor regex fix (also consider double quotes for matching alias)
- more fine grained output config for thisbdm (loglevel 0-5)
- `BDM_THISBDM_NOPROMPT` option

fix and polish `thisbdm`s, and `util.sh`

---

src/core/container/agent_vector.h
src/core/environment/uniform_grid_environment.h
src/core/gpu/cuda_error_chk.h
src/core/gpu/cuda_pinned_memory.cu
src/core/gpu/cuda_pinned_memory.h
src/core/gpu/cuda_timer.h
src/core/gpu/mechanical_forces_op_cuda_kernel.cu
src/core/gpu/mechanical_forces_op_cuda_kernel.h
src/core/operation/mechanical_forces_op_cuda.cc
src/core/operation/mechanical_forces_op_cuda.h
src/core/scheduler.h

* Only use async calls for data transfers and kernel invocations to free the CPUs for other tasks
* Use pinned (non-pageable) memory to avoid one data copy and enable async data transfers
* Optimize filling of columnar buffers
* Fix memory leak
* Add CudaTimer
These changes improved the runtime of the whole soma clustering benchmark by a factor of 2.

Improve CUDA code

---

CONTRIBUTING.md

I updated the URL in the file CONTRIBUTING.md.
The previous URL was outdated and redirected the users to a "error 404" page.
This problem was fixed by simply replacing the URL.

Update URL in CONTRIBUTING.md

---

src/core/simulation.cc
src/core/simulation.h
test/unit/core/container/shared_data_test.cc
test/unit/core/kd_tree_environment_test.cc
test/unit/core/octree_environment_test.cc

Added `SetEnvironment` method to `simulate.h/.cc` such that users can include their custom environments into the simulation. The method is tested in the unit tests for the `OctreeEnvironment` and the `KDTreeEnvironment`.

Set environment

---

cmake/selection.xml
demo/epidemiology/src/behavior.h
src/core/agent/agent.cc
src/core/agent/cell.h
src/core/functor.h
src/core/resource_manager.cc
test/unit/core/functor_test.cc

`LambdaFunctor` is a subclass of `bdm::Functor` that wraps a lambda expression with the same signature and
forwards the call to it.
Together with the function `bdm::L2F` this class allows to define new functors exactly were they are needed and doesn't require the definition of a new class.
Assume the following example:
```
void PrintSmallNeighbors(Agent* agent, double threshold) {
auto functor = L2F([&](Agent* neighbor, double squared_distance)) {
if (neighbor->GetDiameter() < threshold) {
std::cout << neighbor->GetUid() << std::endl;
}
});
auto* ctxt = Simulation::GetActive()->GetExecutionContext();
ctxt->ForEachNeighbor(functor, *agent);
}
```
The base class of `functor` in the example above is `Functor<void, Agent*, double>`
The wrapped lambda is allowed to capture variables.
Without …

Add class LambdaFunctor and function L2F to simplify functor creation

---

CMakeLists.txt

CMake message is now:
```
################################################################
You have just finished to configure the BioDynaMo source.
Compile it by running "ninja".
Before using it do ". /Users/tobias/biodynamo/build/bin/thisbdm.sh".
################################################################
```

Fix typo in source instruction

---

cli/biodynamo.py
cli/build_command.py
cli/common.py
cli/demo_command.py
cli/git_utils.py
cli/new_command.py
cli/print_command.py
cli/run_command.py
cli/util.py

The command `biodynamo new <project>` had a bug, i.e. running it twice with the same `<project>` would just delete the existing folder and crash. Now, it checks if the project exists and, if so, asks the user to overwrite or not.

Add check for existing directory

---

src/core/environment/uniform_grid_environment.h
src/core/execution_context/in_place_exec_ctxt.cc
test/unit/core/environment/uniform_grid_environment_test.cc

* They were causing overloading warnings when compiling with Clang
* They were not used besides in our tests
Also, move the radius checking from the InPlaceExecutionCtxt to the
UniformGridEnvironment implementation. The other environment
implementations were also doing this check internally.
Tests needed to be adapted because the search radius was greater
than the box length

Remove unused UniformGridEnvironment::ForEachNeighbor calls

---

cmake/Testing.cmake

On some systems copying $GTEST_SRC/include would not copy the
contents of the include directory, but rather the include
directory itself - resulting in: biodynamo/build/include/include
This would in return result in Cling not being able to find the
gtest headers and cause a segfault.
The improved copy command will always copy the contents correctly.

Improve copy command for gtest files

---

src/core/analysis/time_series.cc

Add check if at least one time series is defined. The value "total execution time per operation - update time series" for my dummy simulation dropped from ~600 to <5.

Accelerate Timeseries::Update for empty series

---

src/core/container/math_array.h
test/unit/core/container/math_array_test.cc
test/unit/core/model_initializer_test.cc

The `MathArray.Norm()` method returned 1.0 for the zero vector which may not be what users expect. Now it returns 0. As a consequence, `MathArray.Normalize()` will not work for zero vectors any longer which is why we now throw a **_Fatal_** if someone tries to normalize the zero vector. See discussion on slack.

Fix Norm and Normalize for zero vector

---

src/core/container/parallel_resize_vector.h
src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
test/unit/core/container/parallel_resize_vector_test.cc
test/unit/core/diffusion_init_test.cc
test/unit/core/diffusion_init_test.h

The Initialization of the diffusion grid only set the values of one of the two grids while the others remained zero. After the first iteration, we swap the arrays and artificially created zero boundaries resulting in very strange boundary effects. This PR fixes the initialization.
Image was obtained when running the diffusion `EulerGrid` with closed boudaries and inital condition `SetValues(){return 0.5;}`

BugFix for Diffusion Grid Initialization

---

src/core/param/param.h
src/core/simulation.cc
test/unit/core/simulation_test.cc
test/unit/core/visualization/paraview/adaptor_test.cc

Currently, BioDynaMo overrides previous results even if `remove_output_dir_contents` is set to `false`. This is problematic since the simulations can be computationally expensive and you don't want to override them by default. With this PR, we introduce subfolders to the existing output folder structure or the type "YYYY-MM-DD-HH:MM:SS".
For instance, running the `soma_clustering` demo five times results in the following folder structure:
```
~/Programming/biodynamo_projects/soma_clustering on  master! ⌚ 15:21:50
$ tree output 
output
└── soma_clustering
├── 2021-08-10-15:21:43
├── 2021-08-10-15:21:45
├── 2021-08-10-15:21:46
├── 2021-08-10-15:21:48
└── 2021-08-10-15:21:49
6 directories, 0 files
```
I also added tests verifying this.

Avoid overriding results

---

src/core/analysis/time_series.cc
src/core/analysis/time_series.h
src/core/behavior/chemotaxis.h
src/core/behavior/gene_regulation.h
src/core/behavior/secretion.h
src/core/container/inline_vector.h
src/core/diffusion/diffusion_grid.h
src/core/diffusion/euler_grid.h
src/core/diffusion/runga_kutta_grid.h
src/core/diffusion/stencil_grid.h
src/core/memory/memory_manager.cc
src/core/memory/memory_manager.h
src/core/model_initializer.cc
src/core/model_initializer.h
src/core/operation/op_timer.h
src/core/param/command_line_options.cc
src/core/param/command_line_options.h
src/core/resource_manager.h
src/core/util/jit.cc
src/core/util/jit.h
src/core/util/plot_memory_layout.cc
src/core/util/plot_memory_layout.h
src/core/util/timing_aggregator.h
src/core/util/vtune_helper.h
src/core/visualization/root/notebook_util.h
src/core/visualization/visualization_adaptor.cc
src/core/visualization/visualization_adaptor.h

Clang tidy suggest some modification to enhance performance. I separated different suggestions into different commits.
I'm quite confident that the `pass-by-reference`, `std::move` and `fast sting find` are helpful. @LukasBreitwieser at some places, clang tidy suggested `noexcept` and at some other places it complained about the `reinterpret_cast`. The latter is related to [this](https://clang.llvm.org/extra/clang-tidy/checks/performance-no-int-to-ptr.html) clang-tidy flag. Would you mind double-checking?

Clang tidy performance update

---

test/unit/core/container/parallel_resize_vector_test.cc

Fix for:
```
[427/476] Building CXX object CMakeFiles/biodynamo-unit-tests.dir/test/unit/core/container/parallel_resize_vector_test.cc.o
../test/unit/core/container/parallel_resize_vector_test.cc:139:5: warning: explicitly assigning value of variable of type 'ParallelResizeVector<int>' to itself [-Wself-assign-overloaded]
v = v;
~ ^ ~
1 warning generated.
```
See this discussion https://reviews.llvm.org/D45766#1097736

Fix compiler warning for self assignment

---

.github/workflows/macos-system-ci.yml

Scheduled `GHA` on macOS failed because the system was not able to source BDM. To overcome this bottleneck, we now use the `find` command to reliably locate the `bin/thisbdm.sh` script.

Locate `bdm` with `find` in GHA

---

.github/workflows/centos-ci.yml
.github/workflows/centos-system-ci.yml
.github/workflows/macos-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/ubuntu-ci.yml
.github/workflows/ubuntu-system-ci.yml
CMakeLists.txt

We deactivate the `benchmark` build target by default to save time in the build time for developers and users. The option is explicitly activated in GHA to make sure that they keep compiling and do not get out of synchronization with the core of the repository.

Remove `benchmark` as default build target

---

src/core/param/param.cc
src/core/param/param.h
src/core/scheduler.cc
src/core/scheduler.h
src/core/util/progress_bar.cc
src/core/util/progress_bar.h
src/core/util/timing.h

Added a ProgressBar such that one clearly sees the progress of the simulation. Example output:
```
ET = Elapsed Time; TR = Time Remaining
[######                                          ] 135 / 1000 ( ET:  1649, TR:10566)[ms]
```
Examples:
1. No output (default)
```
[bdm-1.3.4] (base) 
~/tmp/soma_clustering/build on  master! ⌚ 12:34:13
$ ./soma_clustering
number of cells in subvolume: 2360
average neighbors in subvolume: 28
correctness coefficient: 0.0157542
Simulation completed successfully!
```
2. Show Simulation step every 100 steps
```
[bdm-1.3.4] (base) 
~/tmp/soma_clustering/build on  master! ⌚ 12:36:10
$ ./soma_clustering  --inline-config '{ "bdm::Param": { "show_simulation_step": 100 } }' 
Time step: 0
Time step: 100
Time step: 200
Time step: 300
Time step: 400
Time step: 500 …
```

Add ProgressBar to visualise progress in `Simulate()`

---

demo/pyramidal_cell/src/pyramidal_cell.h
src/neuroscience/neurite_element.cc
src/neuroscience/neurite_element.h
src/neuroscience/neuron_or_neurite.cc
src/neuroscience/neuron_or_neurite.h
src/neuroscience/neuron_soma.cc
src/neuroscience/neuron_soma.h
test/unit/neuroscience/neuron_soma_test.cc

SWC is a file format that is typically used to store neuron morphologies. While we already have ParaView at hand, the SWC file format establishes the interface to other third-party libraries (e.g. NeuroM of the EPFL) commonly used in that field.

Add SWC export for neurons

---

src/core/diffusion/euler_grid.cc
src/core/diffusion/runge_kutta_grid.cc
src/core/resource_manager.cc
src/core/util/random.cc
src/core/visualization/paraview/vtk_diffusion_grid.cc

First set of fixes addressing issues flagged by Sonar Source Cloud

Some fixes

---

test/unit/core/agent/agent_test.cc
test/unit/core/resource_manager_test.h

This PR fixes the following compiler warnings:
```
[493/533] Building CXX object CMakeFiles/biodynamo-unit-tests.dir/test/unit/core/agent/agent_test.cc.o
/Users/rdm/biodynamo/test/unit/core/agent/agent_test.cc:306:8: warning: unused variable 'nptr' [-Wunused-variable]
auto nptr = neighbor->GetAgentPtr<Cell>();
^
/Users/rdm/biodynamo/test/unit/core/agent/agent_test.cc:350:8: warning: unused variable 'aptr1' [-Wunused-variable]
auto aptr1 = agent1->GetAgentPtr<Cell>();
^
/Users/rdm/biodynamo/test/unit/core/agent/agent_test.cc:356:8: warning: unused variable 'aptr2' [-Wunused-variable]
auto aptr2 = agent2->GetAgentPtr<Cell>();
^
/Users/rdm/biodynamo/test/unit/core/agent/agent_test.cc:399:8: warning: unused variable 'naptr' [-Wunused-variable]
auto naptr = new_agent->GetAgentPtr<Cell>();
^ …
```

Fix compiler warnings

---

src/core/container/math_array.h
test/unit/core/container/math_array_test.cc

Previously:
```cpp
root [1] Double3 x {1,2,3};
root [2] x * 4.0
(bdm::MathArray) { 4.0000000, 8.0000000, 12.000000 }
root [3] 4.0 * x
ROOT_prompt_3:1:5: error: invalid operands to binary expression ('double' and 'bdm::Double3' (aka 'MathArray<double, 3>'))
4.0 * x
~~~ ^ ~
/Users/tobias/tmp/biodynamo/build/third_party/root/include/TH1.h:483:6: note: candidate function not viable: no known conversion from 'bdm::Double3' (aka 'MathArray<double, 3>') to 'const TH1C' for 2nd argument
TH1C operator*(Double_t c1, const TH1C &h1);
^
[... lengthy output ...]
```
Now:
```cpp
root [1] Double3 x {1,2,3};
root [2] x * 4.0
(bdm::MathArray) { 4.0000000, 8.0000000, 12.000000 }
root [3] 4.0 * x
(bdm::MathArray<double, 3UL>) { 4.0000000, 8.0000000, 12.000000 }
```

Add left-multiplication to MathArray

---

src/core/container/math_array.h
src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
test/unit/core/behavior/chemotaxis_test.cc
test/unit/core/container/math_array_test.cc
test/unit/core/diffusion_test.cc
util/installation/osx/prerequisites.sh

This PR makes the `DiffusionGrid::GetGradient` more flexible. It allows retrieving the absolute value of the gradient such that modelers can use the full information of the gradient, e.g. define behaviors that are only executed if the gradient is stronger than a certain threshold. 
Furthermore, the PR introduces a UnitTest to verify that the gradients are computed correctly by comparing an analytic and numeric solution.

Extend DiffusionGrid interface for full gradient information

---

src/core/container/math_array.h
src/core/diffusion/diffusion_grid.cc
test/unit/core/container/math_array_test.cc

Even if gradient.IsZero() is false, gradient.Norm() can evaluate to 0.
e.g. if gradient is: {0, 0, 1.4013e-45}

Fix normalization of the diffusion gradient

---

src/core/agent/agent.h
src/core/agent/agent_pointer.h
src/core/execution_context/execution_context.h
src/core/execution_context/in_place_exec_ctxt.cc
src/core/execution_context/in_place_exec_ctxt.h
src/core/type_index.h
src/neuroscience/neurite_element.cc
src/neuroscience/neurite_element.h
src/neuroscience/neuron_soma.cc
src/neuroscience/neuron_soma.h

In the critical region, disallow duplicates and null pointers.
This can happen, because a call to Agent::CriticalRegion is not protected.
Therefore, another thread can change it before the locks are acquired.

Fix possible race condition in user-defined thread-safety mechanism

---

notebook/ST10-timeseries-plotting-and-analysis.ipynb
src/core/analysis/reduce.h
src/core/analysis/time_series.cc
src/core/analysis/time_series.h
test/unit/core/analysis/reduce_test.cc
test/unit/core/analysis/time_series_test.cc

Encourage the usage of `bdm::experimental::Counter` and `bdm::experimental::GenericReducer`
over their function counterpart.
The class TimeSeries can combine multiple reduce-functors together, resulting in a much 
cache-friendlier data access pattern and thus improved performance.
`TimeSeries::Update` calculates reducer collectors first. This means their results can be used in 
function-style collectors.

Improve the time series collection API

---

demo/epidemiology/render.py

Since ParaView 5.10 the data descriptors of the threshold object have been changed. This PR suggests a change in the rendering process of the epidemiology demo where the PV version is checked and the data descriptors are set accordingly.

Added version check and threshold fix for ParaView in epidemiology demo

---

demo/epidemiology/src/epidemiology.cc
src/core/multi_simulation/database.h
src/core/multi_simulation/experiment.h
src/core/multi_simulation/multi_simulation.cc
src/core/multi_simulation/multi_simulation.h

The check of whether real data was present in our Database class
was always evaluating to true, because it was an object on the
stack. Changed that into a pointer, so that can be evaluated for
nullptr when no Database object is created

Fix warning in multi-simulation mode

---

doc/user_guide/prerequisites.md
util/installation/centos-7/prerequisites.sh
util/installation/osx/prerequisites.sh
util/installation/ubuntu-18.04/prerequisites.sh

The latest version of markupsafe removed `soft_unicode` which is used by jupyter's nbconvert.
Therefore, we hardcode the markupsafe version which still contains the symbol.

Fix issue with markupsafe which breaks nbconvert and thus the website

---

CMakeLists.txt
cmake/UseBioDynaMo.cmake.in
cmake/env/thisbdm.fish
cmake/env/thisbdm.sh

Since OpenMP was updated to version 15.0.3 on MacOS, CMake was unable to locate it. This PR fixes the issue.

Fix macos openmp

---

cmake/UseBioDynaMo.cmake.in

Make LAPACK and BLAS libraries available when using BioDynaMo. Both are already used when building BioDynaMo for the multi-simulation runtime.

Make LAPACK and BLAS libraries available to user code

---

src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
src/core/simulation.cc
test/unit/core/diffusion_test.cc

Add a function `void DiffusionGrid::PrintInfo(std::ostream)` that prints the configuration of the diffusion grid. Sample output:
```
DiffusionGrid: Nutrients
D          = 0.833333
decay      = 1e-05
dx         = 12.6582
max(dt)    <= 32.0461
bounds     : 0 < c < 1
domain     : [-500, 500] x [-500, 500] x [-500, 500]
resolution : 80 x 80 x 80
num boxes  : 512000
```

Add print info member function to `DiffusionGrid`

---

demo/diffusion/src/diffusion.h
demo/flocking/src/flocking.cc
demo/makefile_project/src/makefile_project.h
demo/monolayer_growth/src/monolayer_growth.h
demo/multiple_simulations/src/multiple_simulations.h
demo/pyramidal_cell/src/pyramidal_cell.h
demo/tumor_concept/src/tumor_concept.h
doc/user_guide/diffusion.md
doc/user_guide/tumor_concept.md
src/core/execution_context/execution_context.h
src/core/resource_manager.h

The call `rm->AddAgent` is not thread safe and users should typically use `ctxt->AddAgent`. With this PR, we change the demo code such that future uses will learn to use `ctxt->AddAgent`.

Replace `rm->AddAgent` with `ctxt->AddAgent` in demos

---

src/core/randomized_rm.h
test/unit/core/randomized_rm_test.cc

By default, the random reordering happens at the end of every iterations (during the teardown operation), but with this PR this can be turned off by initializing the `auto_randomize_` variable of the `RandomizedRm` class with `false`. To manually trigger the random reordering of agents, you can call the `RandomizedRm::RandomizeAgentsOrder` function.

Allow both manual and automatic randomization of agents ordering

---

src/core/gpu/gpu_helper.cc
src/core/gpu/opencl_state.cc
src/core/gpu/opencl_state.h
src/core/param/param.h

If a device has multiple GPUs with different floating precision capabilities, only the first GPU's capability is considered. This could lead to double-precision-enabled GPUs being ignored and thus resulting in BioDynaMo not using that GPU.
With this PR we check each GPU for it's FP-precision capability and choose the one that is requested for. If no compatible GPU is found, we throw a Fatal to inform the user that BioDynaMo should be compiled for lower precision.

Enable double precision in OpenCL kernel when compatible GPU is found

---

src/core/diffusion/diffusion_grid.cc
src/core/visualization/paraview/vtk_diffusion_grid.cc
test/unit/core/diffusion_init_test.cc
test/unit/core/visualization/paraview/integration_test.cc

This PR targets issue #311. In this PR, we shift the ParaView export by half a box length. Effectively, this means we change the discretization points from the top left, to the center of the boxes. See below form `x -> o`. We additionally change the initializers for the `DiffusionGrid` because these need to be evaluated at the new discretization points. Two tests needed to be modified in this process as well. 
```
x-----------x-----------x------------
|           |           |           |
|     o     |     o     |     o     |
|           |           |           |
-------------------------------------
x-----------x-----------x------------
|           |           |           |
|     o     |     o     |     o     |
|           |           |           |
------------------------------------- …
```

Fix discretization offsets in DG

---

src/core/behavior/chemotaxis.h
src/core/behavior/secretion.h

Reduce memory footprint, by removing these unused attributes.
The name can be obtained from the diffusion grid.

Remove name attribute from Chemotaxis and Secretion classes

---

src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h

If we have multiple DG but only need the gradient information for one of them, we're doing a lot of unnecessary computation. This PR adds a flag to turn off the gradient computation such that this can be avoided.

Add flag to turn off gradient computation for DG

---

src/core/agent/cell.h
src/core/agent/cell_division_event.h
src/core/analysis/reduce.h
src/core/environment/kd_tree_environment.h
src/core/environment/morton_order.cc
src/core/environment/octree_environment.h
src/core/environment/uniform_grid_environment.h
src/core/execution_context/copy_execution_context.h
src/core/execution_context/in_place_exec_ctxt.h
src/core/multi_simulation/mpi_helper.h
src/core/operation/mechanical_forces_op.h
src/core/operation/mechanical_forces_op_cuda.cc
src/core/operation/reduction_op.h
src/core/operation/visualization_op.h
src/core/resource_manager.cc
src/core/util/plot_memory_layout.cc
src/core/util/random.h
src/core/visualization/paraview/adaptor.h
src/core/visualization/paraview/mapped_data_array.h
src/neuroscience/neurite_element.h
src/neuroscience/neuron_soma.h
src/neuroscience/new_agent_event/neurite_bifurcation_event.h
src/neuroscience/new_agent_event/neurite_branching_event.h
src/neuroscience/new_agent_event/new_neurite_extension_event.h
src/neuroscience/new_agent_event/side_neurite_extension_event.h
src/neuroscience/new_agent_event/split_neurite_element_event.h

Addresses the following code smells: https://sonarcloud.io/project/issues?resolved=false&rules=cpp%3AS3471&types=CODE_SMELL&id=BioDynaMo_biodynamo&open=AX7_qOQL2mRjajNH5Tw0
* [S3471](https://sonarcloud.io/organizations/biodynamo/rules?open=cpp%3AS3471&rule_key=cpp%3AS3471)
* [C++ core guidlines C.128](https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)

Fix function specifiers (virtual, override, final)

---

.github/workflows/centos-ci.yml
.github/workflows/centos-system-ci.yml
.github/workflows/macos-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/repostory-checks.yml
.github/workflows/singularity-integration.yml
.github/workflows/sonar-source.yml
.github/workflows/ubuntu-ci.yml
.github/workflows/ubuntu-system-ci.yml

Add concurrency check to GHA. If you commit to the same branch quickly after each other, this will stop previously launched runs and avoid waiting for previous runs to finish or manually terminating them.

Terminate GHA when branch updates

---

doc/user_guide/Singularity.md

Updated documentation for exporting visualisations on HPC's when using Singularity.

HPC documentation

---

.github/workflows/macos-ci.yml
.github/workflows/macos-system-ci.yml
doc/user_guide/installation.md
doc/user_guide/prerequisites.md

Our support for macOS is founded in the `brew` package manager. `brew` no longer supports macOS 11 and, thus, our macOS 11 CI currently fails. This PR removes support for macOS < 12.0. 
See https://github.com/orgs/Homebrew/discussions/4827#discussioncomment-7189632

Deprecate `macOS` < 12.0 

---

test/unit/core/diffusion_test.cc
util/valgrind-bdm.supp

Change number of diffusion iterations, boundary sizes and resolution of EulerDirichletBoundaries. 
Changed number of diffusion iterations for EulerNeumannZeroBoundaries. 
Changed number of diffusion iterations for EulerNeumannNonZeroBoundaries.

Fix Ubuntu-System-CI

---

doc/user_guide/diffusion.md
src/core/diffusion/diffusion_grid.cc
src/core/diffusion/diffusion_grid.h
src/core/diffusion/euler_depletion_grid.cc
src/core/diffusion/euler_depletion_grid.h
src/core/diffusion/euler_grid.cc
src/core/diffusion/euler_grid.h
src/core/param/param.h
test/unit/core/diffusion_init_test.h
test/unit/core/diffusion_test.cc

This is the pull request for adding periodic boundaries to the diffusion grid. This is simply an extra function on top of Neumann, Dirichlet, open and closed boundaries that the user can choose from. This also includes a unit test to confirm the boundary conditions work. 
Periodic boundaries allows a diffusive substance to move from one boundary to another. This feature is the same as the taurus boundaries for agents, except it is for diffusion. An illustration can be seen below:
|                                                               |
| u0    u1    u2    ............     uN-2    uN-1 |
|                                                               |
When calculating diffusion in u0, it will look at the concentration in u1 and uN-1 to determine the change. If the concentration …

Periodic boundaries

---

.github/workflows/sonar-source.yml

Maybe it's useful in order to debug if the workflow fails, also works with --verbose

Add -X parameter to sonar-scanner for full debug log

---

.github/workflows/centos-system-ci.yml
.github/workflows/macos-system-ci.yml
.github/workflows/ubuntu-system-ci.yml
util/install

This should fix #373. Now the CI ensures that the repository URL is dynamically constructed based on the environment

Updated CI workflows for macOS, Ubuntu and CentOS

---

cmake/utils.cmake

According to #386, since FetchContent_Populate is deprecated we need to get rid of it. This PR makes this possible replacing it with the function `FetchContent_MakeAvailable`

Change FetchContent_Populate to FetchContent_MakeAvailable

---

demo/analytic_continuum/src/continuum_model.h

We add the `final` specifier to the `AnalyticContinuum` class to silence the following warning:
```
[...]/continuum_model.h:30:24: warning: class with destructor marked 'final' cannot be inherited from [-Wfinal-dtor-non-final-class]
~AnalyticContinuum() final = default;
^
[...]/continuum_model.h:26:7: note: mark 'bdm::AnalyticContinuum' as 'final' to silence this warning
class AnalyticContinuum : public ScalarField {
```

Fix compiler warning

---

.github/workflows/repository-checks.yml
.github/workflows/sonar-source.yml
.github/workflows/ubuntu-ci.yml
.github/workflows/ubuntu-system-ci.yml

This PR removes references to `ubuntu-20.04` from the GitHub Actions workflows as the runner will be deprecated on April 15, 2025. The workflows now use only `ubuntu-22.04`.

Remove ubuntu-20.04 from GitHub Actions workflows

---

Singularity

This pull request pins CMake to version 3.19.3 on Singularity file to avoid issues with newer versions (CMake 4.x).

Update Singularity to install CMake 3.19.3 for compatibility
